FROM nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04
ARG PYTHON_VERSION=3.6.9

# use tsinghua source
# https://mirrors.tuna.tsinghua.edu.cn/help/ubuntu/
RUN mv /etc/apt/sources.list /etc/apt/sources.list.bak
RUN echo 'deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial main restricted universe multiverse' >> /etc/apt/sources.list
RUN echo 'deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-updates main restricted universe multiverse' >> /etc/apt/sources.list
RUN echo 'deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-backports main restricted universe multiverse' >> /etc/apt/sources.list
RUN echo 'deb https://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-security main restricted universe multiverse' >> /etc/apt/sources.list

# fix nvidia developer download https://github.com/NVIDIA/nvidia-docker/issues/658#issuecomment-393009761
RUN rm -fr /etc/apt/sources.list.d/cuda.list && rm -fr /etc/apt/sources.list.d/nvidia-ml.list

# basics
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    cmake \
    git \
    curl \
    vim \
    ca-certificates \
    libjpeg-dev \
    libglib2.0 \
    libsm6 \
    libxext6 \
    libgtk2.0-dev \
    libpng-dev \
    wget && \
    rm -rf /var/lib/apt/lists/*

# RUN curl -o ~/miniconda.sh -O https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
COPY Miniconda3-latest-Linux-x86_64.sh Miniconda3-latest-Linux-x86_64.sh
RUN mv Miniconda3-latest-Linux-x86_64.sh ~/miniconda.sh && \
    chmod +x ~/miniconda.sh && \
    ~/miniconda.sh -b -p /opt/conda && \
    rm ~/miniconda.sh && \
    /opt/conda/bin/conda install -y python=$PYTHON_VERSION && \
    /opt/conda/bin/conda clean -ya
ENV PATH /opt/conda/bin:$PATH


RUN conda install mxnet
RUN conda install mxnet-gpu
RUN conda install cudatoolkit
RUN conda install cudnn
RUN conda install tensorflow=1.14.0
RUN conda install tqdm
RUN conda install -c conda-forge opencv
RUN conda install -c anaconda scikit-learn
RUN conda install -c conda-forge scikit-image
RUN conda install keras=2.2.4

# workspace
WORKDIR /workspace                                                                                                                       │
RUN chmod -R a+w /workspace
